language: node_js
node_js:
  - 0.8
before_script: 
  - npm install -g grunt-cli
branches:
  only:
    - master
    - 1.3-stable
    - karma
env:
  - JQUERIES=1.10.2
  - JQUERIES=2.0.3
  - JQUERIES=git
